<?php

/**
 * @file
 * Primary module hooks for ai_elvis module.
 */

/**
 * Implements hook_theme().
 */
function ai_elvis_theme($existing, $type, $theme, $path) {
  return [
    'similar_content_linking' => [
      'variables' => [
        'current_node' => NULL,
        'similar_nodes' => [],
      ],
      'template' => 'similar-content-linking',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for similar_content_linking.
 */
function ai_elvis_preprocess_similar_content_linking(&$variables) {
  // Attach the library for styles and JavaScript.
  $variables['#attached']['library'][] = 'ai_elvis/similar_content_linking';
}

